package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.model.Pessoa;
import javax.swing.JFrame;

/**
 *
 * @author aluno
 */
public class PrincipalForm extends javax.swing.JFrame {

    private static Pessoa pessoaLogada;

    public static Pessoa getPessoaLogada() {
        return pessoaLogada;
    }

    /**
     * Creates new form PrincipalForm
     */
    public PrincipalForm(Pessoa pessoaLogada) {
        this.pessoaLogada = pessoaLogada;
        
        initComponents();
        setVisible(true);
        
        verificarPermissoesUsuarioLogado();
        
        //Maximizar a tela
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        lPessoaLogada.setText(
                "Usuário: "
                + pessoaLogada.getLogin().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lPessoaLogada = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuPessoa = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuContas = new javax.swing.JMenu();
        menuContaCorrente = new javax.swing.JMenuItem();
        menuContaPoupanca = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();
        menuDesconectar = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lPessoaLogada.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lPessoaLogada.setForeground(new java.awt.Color(255, 0, 0));
        lPessoaLogada.setText("Usuário: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPessoaLogada)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(lPessoaLogada)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("Cadastros");

        menuPessoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPessoa.setText("Pessoa");
        menuPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPessoaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPessoa);

        menuProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuProduto.setText("Produto");
        menuCadastro.add(menuProduto);
        menuCadastro.add(jSeparator1);

        menuContas.setText("Contas");

        menuContaCorrente.setText("Conta Corrente");
        menuContas.add(menuContaCorrente);

        menuContaPoupanca.setText("Conta Poupança");
        menuContas.add(menuContaPoupanca);

        menuCadastro.add(menuContas);

        menu.add(menuCadastro);

        jMenu1.setText("Venda");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        menu.add(jMenu1);

        menuRelatorio.setText("Relatórios");
        menu.add(menuRelatorio);

        menuDesconectar.setText("Desconectar");
        menuDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuDesconectarMousePressed(evt);
            }
        });
        menuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDesconectarActionPerformed(evt);
            }
        });
        menu.add(menuDesconectar);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSairMousePressed(evt);
            }
        });
        menu.add(menuSair);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMousePressed
        this.dispose();
    }//GEN-LAST:event_menuSairMousePressed

    private void menuDesconectarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDesconectarMousePressed
        
        //Abrir a tela de login
        new LoginForm();
        
        //Fechar a tela principal
        this.dispose();
        
    }//GEN-LAST:event_menuDesconectarMousePressed

    private void menuPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoaActionPerformed
        
        new PessoaListForm(null, true).setVisible(true);
        
    }//GEN-LAST:event_menuPessoaActionPerformed

    private void menuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesconectarActionPerformed
        this.dispose();
        
        new LoginForm();
    }//GEN-LAST:event_menuDesconectarActionPerformed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        new VendaListForm(null, true)
                .setVisible(true);
    }//GEN-LAST:event_jMenu1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lPessoaLogada;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuContaCorrente;
    private javax.swing.JMenuItem menuContaPoupanca;
    private javax.swing.JMenu menuContas;
    private javax.swing.JMenu menuDesconectar;
    private javax.swing.JMenuItem menuPessoa;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables

    private void verificarPermissoesUsuarioLogado() {
        
        if (pessoaLogada.getLogin().equals("cesar")) {
            menuRelatorio.setVisible(false);
        } else if (pessoaLogada.getLogin().equals("ana")) {
            menuCadastro.setVisible(false);
        }
        
    }
}
